//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: run.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `RunClient`, then call methods of this protocol to make API calls.
public protocol RunClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: RunClientInterceptorFactoryProtocol? { get }

  func runFunction(
    _ request: FunctionParams,
    callOptions: CallOptions?
  ) -> UnaryCall<FunctionParams, Result>
}

extension RunClientProtocol {
  public var serviceName: String {
    return "Run"
  }

  /// Unary call to RunFunction
  ///
  /// - Parameters:
  ///   - request: Request to send to RunFunction.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func runFunction(
    _ request: FunctionParams,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<FunctionParams, Result> {
    return self.makeUnaryCall(
      path: RunClientMetadata.Methods.runFunction.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunFunctionInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension RunClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "RunNIOClient")
public final class RunClient: RunClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: RunClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: RunClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the Run service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: RunClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct RunNIOClient: RunClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: RunClientInterceptorFactoryProtocol?

  /// Creates a client for the Run service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: RunClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol RunAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: RunClientInterceptorFactoryProtocol? { get }

  func makeRunFunctionCall(
    _ request: FunctionParams,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<FunctionParams, Result>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension RunAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return RunClientMetadata.serviceDescriptor
  }

  public var interceptors: RunClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeRunFunctionCall(
    _ request: FunctionParams,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<FunctionParams, Result> {
    return self.makeAsyncUnaryCall(
      path: RunClientMetadata.Methods.runFunction.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunFunctionInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension RunAsyncClientProtocol {
  public func runFunction(
    _ request: FunctionParams,
    callOptions: CallOptions? = nil
  ) async throws -> Result {
    return try await self.performAsyncUnaryCall(
      path: RunClientMetadata.Methods.runFunction.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunFunctionInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct RunAsyncClient: RunAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: RunClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: RunClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol RunClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'runFunction'.
  func makeRunFunctionInterceptors() -> [ClientInterceptor<FunctionParams, Result>]
}

public enum RunClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Run",
    fullName: "Run",
    methods: [
      RunClientMetadata.Methods.runFunction,
    ]
  )

  public enum Methods {
    public static let runFunction = GRPCMethodDescriptor(
      name: "RunFunction",
      path: "/Run/RunFunction",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol RunProvider: CallHandlerProvider {
  var interceptors: RunServerInterceptorFactoryProtocol? { get }

  func runFunction(request: FunctionParams, context: StatusOnlyCallContext) -> EventLoopFuture<Result>
}

extension RunProvider {
  public var serviceName: Substring {
    return RunServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "RunFunction":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<FunctionParams>(),
        responseSerializer: ProtobufSerializer<Result>(),
        interceptors: self.interceptors?.makeRunFunctionInterceptors() ?? [],
        userFunction: self.runFunction(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol RunAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: RunServerInterceptorFactoryProtocol? { get }

  func runFunction(
    request: FunctionParams,
    context: GRPCAsyncServerCallContext
  ) async throws -> Result
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension RunAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return RunServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return RunServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: RunServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "RunFunction":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<FunctionParams>(),
        responseSerializer: ProtobufSerializer<Result>(),
        interceptors: self.interceptors?.makeRunFunctionInterceptors() ?? [],
        wrapping: { try await self.runFunction(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol RunServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'runFunction'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRunFunctionInterceptors() -> [ServerInterceptor<FunctionParams, Result>]
}

public enum RunServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Run",
    fullName: "Run",
    methods: [
      RunServerMetadata.Methods.runFunction,
    ]
  )

  public enum Methods {
    public static let runFunction = GRPCMethodDescriptor(
      name: "RunFunction",
      path: "/Run/RunFunction",
      type: GRPCCallType.unary
    )
  }
}
